<?php

namespace AppBundle\Repository;

/**
 * TapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapaRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginaTapas($pagina=1,$numTapas=3){
        //funcion que devuelve las tapas para una pagina con n elementos
        $query = $this->createQueryBuilder('t')
        ->where('t.top = 1')
        ->setFirstResult($numTapas*($pagina-1))
        ->setMaxResults(3)
        ->getQuery();
        return $query->getResult();
    }
}
